# Importing the basic libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('E:/Anshul/Mentorrbuddy Machine Learning/Project - 2/insurance.csv')
print(dataset)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


# EDA

In [3]:
dataset.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
print('sex')
print(dataset['sex'].value_counts())

sex
male      676
female    662
Name: sex, dtype: int64


In [5]:
print('smoker')
print(dataset['smoker'].value_counts())

smoker
no     1064
yes     274
Name: smoker, dtype: int64


In [6]:
print('region')
print(dataset['region'].value_counts())

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64


In [7]:
print('age Mean and Median :')
print(dataset['age'].mean())
print(dataset['age'].median())
print('bmi Mean and Median :')
print(dataset['bmi'].mean())
print(dataset['bmi'].median())
print('children Mean and Median :')
print(dataset['children'].mean())
print(dataset['children'].median())

age Mean and Median :
39.20702541106129
39.0
bmi Mean and Median :
30.66339686098655
30.4
children Mean and Median :
1.0949177877429
1.0


#### No outliers are present

# Data Preprocessing

## Extracting x and y

In [8]:
x = dataset.iloc[ : ,  :-1 ].values
y = dataset.iloc[ : , -1 ].values

In [9]:
print(x)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [10]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


## Encoding the categorical data

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1,4,5])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x ))
print(x)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.77 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.85 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 0.0 ... 61 29.07 0]]


## splitting x and y into training set and test set    

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y ,random_state = 0, test_size = 0.2)

## Creating and training the ML Model for MLR

In [13]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [14]:
y_pred = reg.predict(x_test)

In [15]:
np.set_printoptions(precision= 2, suppress = True)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[11169.93  9724.53]
 [ 9486.71  8547.69]
 [38181.12 45702.02]
 [16266.31 12950.07]
 [ 6914.65  9644.25]
 [ 3963.48  4500.34]
 [ 1579.4   2198.19]
 [14385.26 11436.74]
 [ 9012.58  7537.16]
 [ 7508.46  5425.02]
 [ 4491.77  6753.04]
 [10279.58 10493.95]
 [ 8801.3   7337.75]
 [ 3798.02  4185.1 ]
 [27926.2  18310.74]
 [10715.12 10702.64]
 [11288.98 12523.6 ]
 [ 6105.02  3490.55]
 [ 8241.04  6457.84]
 [27144.51 33475.82]
 [33644.09 23967.38]
 [14355.1  12643.38]
 [11737.2  23045.57]
 [32137.43 23065.42]
 [ 4170.06  1674.63]
 [ 9254.96  4667.61]
 [ 1084.34  3732.63]
 [ 9804.17  7682.67]
 [ 3771.05  3756.62]
 [10431.86  8413.46]
 [ 9009.32  8059.68]
 [40074.95 48970.25]
 [15688.95 12979.36]
 [13879.45 20630.28]
 [24759.71 14571.89]
 [ 5166.38  4137.52]
 [12610.93  8347.16]
 [30769.1  51194.56]
 [33549.83 40003.33]
 [ 3671.55  1880.49]
 [ 3975.69  5458.05]
 [ 3987.3   2867.12]
 [30528.58 20149.32]
 [39505.3  47496.49]
 [27810.5  36149.48]
 [ 5092.59 26018.95]
 [10604.25 19749.38]
 [ 7829.52  6

## mse, rmse, r2_score (Before Backward Elimination)

In [16]:
import sklearn.metrics as met
mse = met.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = met.r2_score(y_test, y_pred)

In [17]:
print('Mean Squared Error : ', mse)
print('Root Mean Squared Error : ', rmse)
print('R2_Score : ', r2)

Mean Squared Error :  31827950.229523778
Root Mean Squared Error :  5641.626558850185
R2_Score :  0.7999876970680437


## Backward Elimination

In [18]:
X_back = x[ : , 1 : ]
X_back = np.append(arr = np.ones((1338, 1)).astype(int), values = X_back, axis = 1)
print(X_back)

[[1 0.0 0.0 ... 19 27.9 0]
 [1 1.0 1.0 ... 18 33.77 1]
 [1 1.0 1.0 ... 28 33.0 3]
 ...
 [1 0.0 1.0 ... 18 36.85 0]
 [1 0.0 1.0 ... 21 25.8 0]
 [1 0.0 0.0 ... 61 29.07 0]]


In [19]:
import statsmodels.api as sm
def backward_elimination(x, SL):
    numCol = len(x[0])
    for i in range(0, numCol):
        regressor_OLS = sm.OLS(endog = y, exog = x).fit()
        maxCol = max(regressor_OLS.pvalues).astype(float)
        if maxCol > SL:
            for j in range(0, numCol - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxCol):
                    x = np.delete(x, j, axis = 1)
                    print(regressor_OLS.summary())
    print(regressor_OLS.summary())
    return x

In [20]:
X_opt = np.array(x[:, :], dtype = float)
X_opt = backward_elimination(X_opt, 0.05)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     500.8
Date:                Mon, 06 Jul 2020   Prob (F-statistic):               0.00
Time:                        19:14:48   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1329   BIC:                         2.716e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          -201.1179    418.353     -0.481      0.6

In [21]:
print(X_opt)

[[ 0.    1.   19.   27.9   0.  ]
 [ 1.    0.   18.   33.77  1.  ]
 [ 1.    0.   28.   33.    3.  ]
 ...
 [ 1.    0.   18.   36.85  0.  ]
 [ 1.    0.   21.   25.8   0.  ]
 [ 0.    1.   61.   29.07  0.  ]]


## splitting x and y into training set and test set 

In [22]:
x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(X_opt, y ,random_state = 0, test_size = 0.2)

## Creating and training the ML Model for MLR

In [23]:
reg.fit(x_train_1, y_train_1)

LinearRegression()

In [24]:
y_pred_1 = reg.predict(x_test_1)

In [25]:
print(np.concatenate((y_pred_1.reshape(len(y_pred_1), 1), y_test_1.reshape(len(y_test_1), 1)), 1))

[[11461.22  9724.53]
 [ 9920.25  8547.69]
 [37782.65 45702.02]
 [15948.08 12950.07]
 [ 6880.18  9644.25]
 [ 3611.72  4500.34]
 [ 1116.04  2198.19]
 [14050.37 11436.74]
 [ 8755.91  7537.16]
 [ 7245.24  5425.02]
 [ 4141.89  6753.04]
 [10105.76 10493.95]
 [ 9070.29  7337.75]
 [ 4297.77  4185.1 ]
 [27698.89 18310.74]
 [11158.3  10702.64]
 [11185.2  12523.6 ]
 [ 5566.18  3490.55]
 [ 8020.78  6457.84]
 [26614.64 33475.82]
 [33491.4  23967.38]
 [14072.29 12643.38]
 [11247.09 23045.57]
 [32583.5  23065.42]
 [ 4526.14  1674.63]
 [ 8649.41  4667.61]
 [  772.17  3732.63]
 [10160.38  7682.67]
 [ 4246.31  3756.62]
 [10201.55  8413.46]
 [ 8778.52  8059.68]
 [40341.15 48970.25]
 [15888.84 12979.36]
 [14071.98 20630.28]
 [24375.44 14571.89]
 [ 4693.49  4137.52]
 [12917.27  8347.16]
 [30917.3  51194.56]
 [33245.26 40003.33]
 [ 3865.5   1880.49]
 [ 3634.32  5458.05]
 [ 4441.73  2867.12]
 [30088.45 20149.32]
 [39174.93 47496.49]
 [28081.32 36149.48]
 [ 4782.78 26018.95]
 [11052.5  19749.38]
 [ 7665.9   6

## mse, rmse, r2_score (After Backward Elimination)

In [26]:
mse_1 = met.mean_squared_error(y_test_1, y_pred_1)
rmse_1 = np.sqrt(mse_1)
r2_1 = met.r2_score(y_test_1, y_pred_1)

In [27]:
print('Mean Squared Error : ', mse_1)
print('Root Mean Squared Error : ', rmse_1)
print('R2_Score : ', r2_1)

Mean Squared Error :  32171708.572455727
Root Mean Squared Error :  5672.01098134125
R2_Score :  0.7978274606303823
